version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      # If you need to pass any environment variables to your PHP app
      DB_HOST: db
      DB_NAME: myapp
      DB_USER: username
      DB_PASS: password

  db:
    image: postgres:16-alpine
    container_name: domain_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
