version: "3.8"

services:
  app:
    build: .
    container_name: php_domain_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: domain_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
